# LabPython - AHP/MCDM - Bombeiros - 11/24

# Bernardo Truccolo Schettini

## Imports e defs

In [1]:
import numpy as np
import sympy as sp
from sympy import symbols


In [2]:
def array(I):

  return np.array(I)

def dot(u,v):

    return np.dot(u,v)

def max(A):
    return np.max(A)

def mean(A):
    return np.mean(A)

def somaC(matriz):
    return np.sum(matriz, axis=0)

def somaL(matriz):
    return np.sum(matriz, axis=1)

# Definida as matrizes de comparação, o vetor de prioridade relativa é determinado por um auto
# vetor que viabilizará a determinação do grau de importância dos elementos em cada nível
# hierárquico, sendo esta a fase de priorização dos elementos do sistema.

#NC = Normalizar coluna
#MN = Matriz Normalizada

def NC(M):
    # Calcula a soma de cada coluna
    soma_colunas = somaC(M)
    
    # Divide cada elemento da coluna pela soma da coluna correspondente
    matriz_normalizada = M / soma_colunas
    
    return matriz_normalizada

def round(a,n):
    return np.round(a,n)


def append(X, a):

    return np.append(X,a)

## 1) Introdução

In [3]:
# Com este documento, o objetivo é reproduzir o que foi feito no artigo "ESTUDO PARA LOCALIZAÇÃO
# DE UNIDADE DO CORPO DE BOMBEIROS UTILIZANDO ANÁLISE MULTICRITÉRIO" de Leandro de Oliveira Silva,
# Vinicius Blancato Oliveira e Bruno Henrique de Paula em python. 

## 2) Resumo do trabalho escolhido

In [4]:
# O artigo tem o objetivo de tratar as ações de preparação à
# eventos emergenciais ao propor um estudo de decisão de escolha de localização para postos
# avançados de atendimento de corpo de bombeiros pelo método Analytic Hierarchy Process (AHP) 
# e aproximar o tempo de resposta das ocorrências ao padrão internacional de atendimento.

In [5]:
# Neste documento será replicado o processo de AHP feito no artigo e será explicado a teoria por trás.

## 3) Método AHP

In [6]:
# O Método AHP tem como base a representação de um problema complexo através da
# estruturação hierárquica, objetivado a priorizar os fatores na análise das diversas alternativas.

# O Método AHP assume que um conjunto de critérios tenha sido estabelecido, e
# que está tentando estabelecer um conjunto normalizado de pesos para ser usado quando as
# alternativas que usam critérios estejam sendo comparada

# O processo de estruturação da AHP pode ser resumida como:

# 1) Desenvolver hierarquia de problema gráfica;
# 2) Construir matriz par a par de comparação;
# 3) Sumarizar
# 4) Submeter ao teste de consistência
# 5) Todos os julgamentos estão ok? Sim -> Processgue, Não -> Volte para 2;
# 6) Todos os niveis são comparados? Sim -> Processgue, Não -> Volte para 2;
# 7) Desenvolver classificação geral de prioridade.

## 4) Descrição do método AHP

In [7]:
# De acordo com Saaty (1991), um problema de decisão envolve os seguintes elementos:
# conjunto de alternativas ou soluções; conjunto de critérios ou atributos; e conjunto de
# consequências da implementação de cada alternativa.

#A estratégia do Método AHP consiste em:
# 1- criar matrizes de preferência para cada critério e para cada alternativa; 2- normalizá-las;
# 3- obter a média de cada uma delas; 4- construir a matriz de prioridade; 5- realizar a comparação dos
# critérios para se obter um resultado final, após a obtenção dos vetores de prioridades ou de
# impactos das alternativas sob cada critério e calcula a ocorrência do método para o problema
# em análise.

# A construção da Matriz de Preferência para cada Critério utiliza-se a escala fundamental de
# Saaty (1991), os quais são comparados a fim de permitir a construção de uma matriz de
# decisão (são 9 critérios avaliados, sendo recomendado de 3 a 7 critérios para que o resultado
# o método seja consistente):

# 1 - Ambos elementos são de importância - Ambos elementos contribuem com a prioridade de igual forma;
# 3 - Moderada importância de um elemento sobre o outro - A experiência e a opinião favorecem um elemento sobre o outro;
# 5 - Forte importância de um elemento sobre o outro - Um elemento é fortemente favorecido;
# 7 - Importância muito forte de um elemento sobre sobre o outro - Um elemento é fortemente favorecido sobre o outro;
# 9 - Extrema importância sobre o outro - Um elemento é favorecido pelo menos com uma ordem de magnitude de diferênça;
# 2,4,6,8 - Valores intermedários entre as opiniões adjacentes - Usados como valores de consenso entre opiniões;
# Incremento 0,1 - Valores intermediários na graduação mais fina de 0,1 - Usados para graduação mais finas das opiniões.


## 5) Aplicação do AHP

In [8]:
# Para a aplicação do Método AHP e a escolha da melhor localização de unidades do corpo de
# bombeiros para atendimento aos padrões internacionais, a cidade de Uberaba do Estado de
# Minas Gerais é escolhida. A população de Uberaba vem tendo um crescimento em sua
# densidade populacional e consequentemente um crescimento do número de solicitações de
# emergência e urgência aos órgãos de atendimento local. E, além deste crescimento, a
# população apresenta uma alteração do perfil jovem para a idosa (IBGE, 2016).

### 5.1) Conceituação do corpo de bombeiros local

In [ ]:
# Desde sua implantação, as características e
# o perfil da cidade modificaram, destacando a ampliação da área urbana, do número de
# habitantes, número de veículos leves e pesados, ritmo de trânsito mais acelerado.

# Por estes fatos, algumas questões podem ser questionadas, como: a quantidade de unidades de
# atendimento é suficiente para atender à cidade?; a localização da disponibilidade dos serviços
# de atendimento as ocorrências de urgência e emergência são ideais?; o tempo resposta
# ideal está sendo atendido?; como melhorar este panorama e ofertar um serviço de melhor
# qualidade para a população?

### 5.2) Informação utilizadas no estudo

In [ ]:
# Para validação e confiança nos dados apresentados no Método AHP, são analisados 12.912
# dados de atendimento a ocorrências para a cidade de Uberaba, compreendidos entre o
# período de janeiro de 2010 a março de 2013.

# Dentre todas as opções de localidades a serem estudadas, analisando as estatísticas de
# ocorrências e o mapa da cidade de Uberaba, decidiu-se por dividir a cidade em quatro zonas
# espaciais como alternativas de localização (Zona Norte, Zona Sul, Zona Leste e Zona Oeste).

# Após validação, foram escolhidos os seguintes critérios: 1 - Frequência, 2 - infraestrutura e 3 - desenvolvimento.
# Com os seguintes subcritérios: 

### 5.3) Aplicação do AHP para localização

In [ ]:
# A estratégia do Método AHP consiste em (1) criar matrizes de preferência para cada critério e
# para cada fornecedor, (2) normalizá-las, (3) obter a média de cada uma delas, (4) construir a matriz de prioridade, (5) realizar a comparação dos critérios para se obter um
# resultado final. Após a obtenção dos vetores de prioridades ou de impactos das alternativas
# sob cada critério, (6) calcular a ocorrência do método para o problema em análise.

# Para iniciar a aplicação do método AHP no auxílio da decisão proposta, analisam-se os
# critérios escolhidos, dando pesos para cada um deles, de acordo com a importância que é dada
# para cada um destes, na visão de um estudante em fase de escolha de carreira.

# Após, realizaram uma tabela com as probabilidades de ocorrências de incêndios
# de cada zona em relação aos subcritérios e critérios, para criar a matriz de preferência.

In [3]:
# Matriz 3x3 
# (Colunas/Linhas = Tempo de resposta / N° de ocorrência / Grau de importância)
# Critério 1: Frequência
C1 = ([ 1, 7, 7],
     [1/7, 1, 5],
     [1/7, 1/5, 1])

C1 = array(C1)
C1.shape

# Matriz 3x3 
# (Colunas/Linhas = Unidade de saúde / Distância/acesso / risco para corporação)
# Critério 2: Infraestrutura
C2 = ([1, 1/5, 2],
      [5, 1, 7],
      [1, 1/7, 1])

C2 = array(C2)

# Matriz 5x5 
# (Colunas/Linhas = Comercial / residencial / rural / industrial / poder aquisitivo
# Critério 3: Desenvolvimento

C3 = ([1, 1, 4, 2, 4],
      [1, 1, 4, 2, 4],
      [1/4, 1/4, 1, 3/2, 1/3],
      [1/2, 1/2, 2/3, 1, 1/3],
      [1/4, 1/4, 3, 3, 1])

C3 = array(C3)
C1

array([[1.        , 7.        , 7.        ],
       [0.14285714, 1.        , 5.        ],
       [0.14285714, 0.2       , 1.        ]])

In [8]:
# Definida as matrizes de comparação, o vetor de prioridade relativa é determinado por um auto
# vetor que viabilizará a determinação do grau de importância dos elementos em cada nível
# hierárquico, sendo esta a fase de priorização dos elementos do sistema.

NC1 = NC(C1)
NC2 = NC(C2)
NC3 = NC(C3)

NC2

array([[0.14285714, 0.14893617, 0.2       ],
       [0.71428571, 0.74468085, 0.7       ],
       [0.14285714, 0.10638298, 0.1       ]])

In [9]:
#vetor media

NCM1 = somaL(NC1)/3
NCM2 = somaL(NC2)/3
NCM3 = somaL(NC3)/5



In [9]:
#Autovetor

AV1 = dot(C1,P1)
w = ([P1[0]],
     [P1[1]],
     [P1[2]])

print(AV1)
dot(C1,w)

AV2 = dot(C2,P2)
AV3 = dot(C3,P3)

print(AV1[0])

[2.66020429 0.66326176 0.21531513]
2.6602042943506357


In [10]:
# Tabela Critério 1:

print('Critério 1:')
print('Subcritério          |  Auto Vetor |  Normalização')
print('Tempo de resposta    |', round(AV1[0],2), '       | ', round(P1p[0],2),'%')  
print('N° de ocorrências    |', round(AV1[1],2), '       | ', round(P1p[1],2),'%') 
print('Grau de importâncias |', round(AV1[2],2), '       | ', round(P1p[2],2),'%') 
print('Total                |', round(sum(AV1),2),'       | ', round(sum(P1p),2),'%') 

Critério 1:
Subcritério          |  Auto Vetor |  Normalização
Tempo de resposta    | 2.66        |  72.33 %
N° de ocorrências    | 0.66        |  20.59 %
Grau de importâncias | 0.22        |  7.08 %
Total                | 3.54        |  100.0 %


In [11]:
# Tabela Critério 2:

print('Critério 2:')
print('Subcritério           |  Auto Vetor |  Normalização')
print('Unidade de saúde      |', round(AV2[0],2), '       | ', round(P2p[0],2),'%')  
print('Distância/acesso      |', round(AV2[1],2), '       | ', round(P2p[1],2),'%') 
print('Risco para corporação |', round(AV2[2],2), '       | ', round(P2p[2],2),'%') 
print('Total                 |', round(sum(AV2),2),'       | ', round(sum(P2p),2),'%') 

Critério 2:
Subcritério           |  Auto Vetor |  Normalização
Unidade de saúde      | 0.54        |  16.39 %
Distância/acesso      | 2.35        |  71.97 %
Risco para corporação | 0.38        |  11.64 %
Total                 | 3.28        |  100.0 %


In [12]:
# Tabela Critério 3:

print('Critério 3:')
print('Subcritério  |  Auto Vetor |  Normalização')
print('Comercial    |', round(AV3[0],2), '       | ', round(P3p[0],2),'%')  
print('Residencial  |', round(AV3[1],2), '       | ', round(P3p[1],2),'%') 
print('Rural        |', round(AV3[2],2), '       | ', round(P3p[2],2),'%') 
print('Industrial   |', round(AV3[3],2), '       | ', round(P3p[3],2),'%') 
print('Poder        |', round(AV3[4],2), '        | ', round(P3p[4],2),'%') 
print('Total        |', round(sum(AV3),2),'       | ', round(sum(P3p),2),'%') 

Critério 3:
Subcritério  |  Auto Vetor |  Normalização
Comercial    | 1.86        |  32.14 %
Residencial  | 1.86        |  32.14 %
Rural        | 0.46        |  8.76 %
Industrial   | 0.54        |  10.51 %
Poder        | 0.9         |  16.45 %
Total        | 5.63        |  100.0 %


In [10]:
# Inteirado os autos vetores e normalizações em cada subcritério, o próximo estágio da análise é
# normalizar os critérios de cada zona locacional na cidade de Uberaba (sul, leste, oeste e
# norte) com base aos subcritérios de maior destaque: tempo de resposta, distância/acesso,
# comercial e residencial.

# Matriz 5x5
# Linha/Coluna: Zona Sul, Zona Leste, Zona Oeste, Zona Norte e Auto vetor
# comparação dos candidatos ao subcritério tempo de resposta
Z = ([1, 3, 5, 7],
     [round(1/3,2), 1, 3, 5],
     [round(1/5,2), round(1/3,2), 1, 2],
     [round(1/7,2), round(1/5,2), round(1/2,2), 1])

Z = array(Z)
print(Z)
somaC(Z)

[[1.   3.   5.   7.  ]
 [0.33 1.   3.   5.  ]
 [0.2  0.33 1.   2.  ]
 [0.14 0.2  0.5  1.  ]]


array([ 1.67,  4.53,  9.5 , 15.  ])

In [14]:
# auto vetores de Z (vetor media)

NZ = NC(Z)
MZ = somaL(NZ)/4
MZp = MZ*100

MZ

array([0.56350913, 0.26686954, 0.10780116, 0.06182017])

In [25]:
#O processo na matriz Z, foi repetido para realizsar as matrizes de comparação entre os candidatos e os demais subcritérios julagados mais importantes
# Contudo, eles não são mostrados no documento, comente a matriz de prioridade em porcetnagem, ela segue a seguinte matriz:

p = ([.558,.6185,.1927,.365],
          [.2607,.2057,.4992,.1250],
          [.1053,.0868,.0655,.125],
          [.0603,.054,.219,.375])

p = array(p)
p.shape
p
# Linhas: Zona sul, leste, oeste, norte
# Colunas: Tempo-resposta, distancia/acesso, comercial, residencial
#cada coluna são os vetores como o MZ, no qual é o vetor media dos candidatos aos subcriterios

array([[0.558 , 0.6185, 0.1927, 0.365 ],
       [0.2607, 0.2057, 0.4992, 0.125 ],
       [0.1053, 0.0868, 0.0655, 0.125 ],
       [0.0603, 0.054 , 0.219 , 0.375 ]])

In [37]:
#comparação dos subcritérios a eles mesmos

L = ([1, 7, 5, 5],
     [1/7,1 , 3,3],
     [1/5, 1/3,1 ,1],
     [1/5, 1/3, 1,1])

L = array(L)
L

#ordem de coluna/linha: Tempo-resposta, distancia/acesso, comercial, residencial

NL = NC(L)
ML = somaL(NL)/4
ML

resultado = dot(p,ML)

resultado


array([0.51884433, 0.25905026, 0.09971345, 0.10259103])

In [39]:
print('Preferência da Zona Sul = ', round(resultado[0]*100,2), 
      '%, Zona Leste =', round(resultado[1]*100,2), '%, Zona Oeste = ', 
      round(resultado[2]*100,2), '%, Zona Norte =', round(resultado[3]*100,2),'%.')

Preferência da Zona Sul =  51.88 %, Zona Leste = 25.91 %, Zona Oeste =  9.97 %, Zona Norte = 10.26 %.


In [ ]:
# De posse destes dados, o índice de consistência (IC) e a razão de consistência (RC) são
# analisados, observando se o auto vetor máximo é igual a n (dimensão da matriz). Ao aplicar a
# RC, obtém-se uma coerência deste estudo igual a 8,33% considerando-o satisfatório, pois
# segundo a metodologia apresenta por Saaty (1991) o índice de consistência menor do que 0,1 é
# visto como consistente para prosseguir com os cálculos do AHP e caso for maior do que 0,1
# recomenda-se que os julgamentos sejam refeitos.

## 6) Conclusão

In [ ]:
# Os resultado finais para o processo de decisão são fornecidos em percentual de identificação da
# melhor zona a localizar a unidade de atendimento à população, destacando: 59.88% à zona sul,
# 19,76% à zona leste, 11,98% à zona oeste e 8.38% à zona norte da cidade de Uberaba.

In [ ]:
# Ao analisar os dados obtidos no método multicritério AHP constata-se que a zona que
# deve ser instalada a unidade de atendimento à população é a zona sul, com uma indicação de
# 52,06% sobre as demais zonas analisadas. No entanto, somente indicar a z ona Sul da
# cidade para a localização deixa um pouco ampla a decisão do gestor, podendo ainda ocorrer
# desvios na decisão, visto isto e analisando as estatísticas e a viabilidade das demais zonas
# decidiu-se por estar indicando cinco opções de bairros que melhor de aplicam ao estudo,
# sendo eles região sul do bairro Abadia, Costa Teles, Parque das Gameleiras, Parque São
# Geraldo e Vila São Vicente.

## Testes

In [93]:
A = ([1,2,2],[2,3,1])
B = ([1,2],[1,1],[0,1])

dot(A,B)

array([[3, 6],
       [5, 8]])

In [261]:
somaC(NZp)[0]

100.00000000000001

In [262]:
PQp

array([61.44161843, 20.1595633 ,  9.19940914,  9.19940914])