# Bernardo T Schettini - 154235
## 02/2025

In [1]:
# Realizar o problema de transporte mostrado no artigo "PROGRAMAÇÃO LINEAR: UMA SOLUÇÃO ALTERNATIVA PARA O PROBLEMA DE TRANSPORTE", onde trabalho de pesquisa tem por objetivo apresentar um método de resolução alternativo para o
# problema de transporte em programação linear (PL), sendo que o método comumente empregado para solucionar este problema é o método simplex. Neste trabalho realiza-se uma
# aplicação em um problema de transporte de uma indústria de pneus, onde existem centros de produções e centros de armazenamento, os requisitos clássicos para o problema de transporte.
# Com esta aplicação prática aplicam-se os dois métodos de resolução, o método simplex e o método de resolução por quadros (Não decidido por qual vou fazer).

## Imports & Defs

In [1]:
import numpy as np
import sympy as sp
from sympy import symbols

In [77]:
def array(I):

  return np.array(I)

def dot(u,v):

    return np.dot(u,v)

def max(A):
    return np.max(A)

def min(A):
    return np.min(A)

def coluna(M, n):
    return M[:,n]

def linha(M,n):
    return M[n,:]

def MI(n):

   
    return np.eye(n, dtype=int)

def copy(M):

    return M.copy()

## O problema

In [4]:
# Uma indústria de Pneus tem duas fábricas, a fábrica 1 e a fábrica 2 com produções de 800 e 1200 peças de pneus por mês, Esta produção é armazenada em deposito de vendas, o deposito 1, deposito
# 2 e deposito 3, que tem capacidade de armazenamento mensal de 750, 920 e 330 peças de pneus respectivamente. Os custos para o transporte destas peças para os depósitos estão expressos na
# tabela a seguir:

#Fábricas \ Colunas |   1    |   2   |   3
#          1        |   15   |   10  |   8
#          2        |    13  |   9   |   20



# Modelagem:


# xij { i -> frabricas, i =1, 2; j -> depositos, j = 1, 2, 3

# Max Z(x) = 15x11 + 10x12 + 8x13 + 13x21 + 9x22 + 20x23
#Sujeito a:

# x11 + x12 + x13 =< 800  } Restrições de Produção
# x21 + x22 + x23 =< 1200 }

# x11 + x21 =< 750} Restrições de produção
# x12 + x22 =< 920}
# x13 + x23 =< 320}

# x11,x12,x13,x21,x22,x23 >= 0

In [5]:
# -Min Z(x) = -15x11 - 10x12 - 8x13 - 13x21 - 9x22 - 20x23
#Sjeito a:

# x11 + x12 + x13 + S1 = 800  } Restrições de Produção
# x21 + x22 + x23 + S2 = 1200 }

# x11 + x21 + S3 = 750} Restrições de produção
# x12 + x22 + S4 = 920}
# x13 + x23 + S5 = 320}

# x11,x12,x13,x21,x22,x23 >= 0
# S1,S2,S3,S4,S5 >= 0

#Onde Sn são variáveis artificiáis, as quais possibilitam o problema ter uma base ótima (Identidade)

In [4]:
#Custos
C = array([-15, -10, -8, -13, -9, -20, 0, 0, 0, 0, 0]) #x11,x12,x13,x21,x22,x23,S1,S2,S3,S4,S5
Cb = array([0, 0, 0, 0, 0]) #S1,S2,S3,S4,S5
Cn = array([-15, -10, -8, -13, -9, -20]) #x11,x12,x13,x21,x22,x23

print(Cb)

# Matriz de restrições
#     x11 x12 x13 x21 x22 x23 S1 S2 S3 S4 S5
A = ([ 1,  1,  1,  0,  0,  0, 1, 0, 0, 0, 0],
     [ 0,  0,  0,  1,  1,  1, 0, 1, 0, 0, 0],
     [ 1,  0,  0,  1,  0,  0, 0, 0, 1, 0, 0],
     [ 0,  1,  0,  0,  1,  0, 0, 0, 0, 1, 0], 
     [ 0,  0,  1,  0,  0,  1, 0, 0, 0, 0, 1])

A = array(A)
print(A)

#    x11 x12 x13 x21 x22 x23 S1   S2    S3   S4  S5
X = (0,   0,  0,  0,  0,  0, 800, 1200, 750, 920, 320)
X = array(X)

#Base = S1, S2, S3, S4, S5
#Não-Base = x11,x12,x13,x21,x22,x23

B = (coluna(A,6), coluna(A,7), coluna(A,8), coluna(A,9), coluna(A,10))

B = array(B)
Bi = B
print(Bi)

[0 0 0 0 0]
[[1 1 1 0 0 0 1 0 0 0 0]
 [0 0 0 1 1 1 0 1 0 0 0]
 [1 0 0 1 0 0 0 0 1 0 0]
 [0 1 0 0 1 0 0 0 0 1 0]
 [0 0 1 0 0 1 0 0 0 0 1]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [5]:
#1) C^t B (custos base) * B^-1

Cb_Bi = dot(Cb, Bi)

Cb_Bi

array([0, 0, 0, 0, 0])

In [6]:
#2) C^k = Ck - (C^t B * B^-1) = Ctb_Bi * Ak (k = Non: 1 (x1) e 2 (x2))
# Menor C^k entra

Ck = []

#x11

Cx11 =  Cn[0] - dot(Cb_Bi,coluna(A,0))
Cx11
Ck.append(Cx11)

#x12

Cx12 =  Cn[1] - dot(Cb_Bi,coluna(A,1))
Cx12
Ck.append(Cx12)

#x13
Cx13 =  Cn[2] - dot(Cb_Bi,coluna(A,2))
Cx13
Ck.append(Cx13)

#x21
Cx21 =  Cn[3] - dot(Cb_Bi,coluna(A,3))
Cx21
Ck.append(Cx21)

#x22
Cx22 =  Cn[4] - dot(Cb_Bi,coluna(A,4))
Cx22
Ck.append(Cx22)

#x23
Cx23 =  Cn[5] - dot(Cb_Bi,coluna(A,5))
Cx23
Ck.append(Cx23)


print(Ck)
print('O minimo é',min(Ck),', do x23, logo é candidato a entrar a base B.')

[-15, -10, -8, -13, -9, -20]
O minimo é -20 , do x23, logo é candidato a entrar a base B.


In [7]:
#3) Ck  > 0?


if min(Ck) > 0:
    print('Solução ótima.')

else: 
    print('Não é solução ótima, prossiga ao próximo passo.')

Não é solução ótima, prossiga ao próximo passo.


In [59]:
#4) dB = -B^-1Ak (k = 23, xn que entra)

dB = -(Bi*coluna(A,5))
print(dB)

#dS1 = 0, dS2 = -1, dS3 = 0, dS4 = 0, dS5 = -1

#       x11 x12 x13 x21 x22 x23 S1 S2 S3 S4 S5
dx23 = ( 0,  0,  0,  0,  0,  1, 0, -1, 0, 0, -1)
dx23 = array(dx23)
dx23



[[ 0  0  0  0  0]
 [ 0 -1  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0 -1]]


array([ 0,  0,  0,  0,  0,  1,  0, -1,  0,  0, -1])

In [60]:
#5) lambda = l, lB(n) = lk = - xn/dn -> min(lB) = qual xB sai da base

print(X, dx23)

# dS1, dS3 e dS4 não vão já que são zero

l = []

#S2
lS2 = -(X[7]/dx23[7])
lS2
l.append(lS2)

#S5
lS5 = -(X[10]/dx23[10])
lS5
l.append(lS5)

lb = min(l)

print(l,lb)
print('O minimo é',lb,', do dS5 logo S5 sai da base B.')




[   0    0    0    0    0    0  800 1200  750  920  320] [ 0  0  0  0  0  1  0 -1  0  0 -1]
[1200.0, 320.0] 320.0
O minimo é 320.0 , do dS5 logo S5 sai da base B.


In [61]:
#6) 
#X' (X' == Xa) = X + lb*d

Xa = X + lb*dx23
print(Xa, X)

[  0.   0.   0.   0.   0. 320. 800. 880. 750. 920.   0.] [   0    0    0    0    0    0  800 1200  750  920  320]


## Simplex

In [34]:
cb = array([0, 0, 0, 0, 0])
cn = array([15, 10, 8, 13, 9, 20])
Cb = array([1, 1, 1, 1, 1])
Cn = array([0, 0, 0, 0, 0, 0])
b = array([800, 1200, 750, 920, 330])

      


N = ([1, 1, 1, 0, 0, 0],
     [0, 0, 0, 1, 1, 1],
     [1, 0, 0, 1, 0, 0],
     [0, 1, 0, 0, 1, 0],
     [0, 0, 1, 0, 0, 1])
#print(dot(dot(cb,Bi),b))
#print(dot(dot(Cb,Bi),b))

Bi = MI(5)

N =array(N)

cn_ = dot(dot(cb,Bi),N) - cn
print('cn_ = cb Bi N - cn:', cn_)

Cn_ = dot(dot(Cb,Bi),N) - Cn
print('Cn_ = Cb Bi N - Cn:', Cn_)

print('cb Bi b:',dot(dot(cb,Bi),b), ', Cb Bi b:' ,dot(dot(Cb,Bi),b))

cn_ = cb Bi N - cn: [-15 -10  -8 -13  -9 -20]
Cn_ = Cb Bi N - Cn: [2 2 2 2 2 2]
cb Bi b: 0 , Cb Bi b: 4000


In [158]:
# Ordem das colunas da tabela: X11, X12, X12, X21, X22, X23, S1, S2, S3, S4, S5, RHS
# Ordem das linhas da tabela: X0, S1, S2, S3, S4, S5

#1° iteração

A = ([ 2,  2,  2,  2,  2,  2, 0, 0, 0, 0, 0, 4000],
     [ 1,  1,  1,  0,  0,  0, 1, 0, 0, 0, 0, 800],
     [ 0,  0,  0,  1,  1,  1, 0, 1, 0, 0, 0, 1200],
     [ 1,  0,  0,  1,  0,  0, 0, 0, 1, 0, 0, 750],
     [ 0,  1,  0,  0,  1,  0, 0, 0, 0, 1, 0, 920], 
     [ 0,  0,  1,  0,  0,  1, 0, 0, 0, 0, 1, 330])


A = array(A)
print('A:')
print(A)
#Vamos começar com o X11, tem 1 em S1 e S3, para verificar qual deles sai, divida RHS/Sn, menor valor indicará qual sairá.

print('----------------------------------------------------------------')

#Neste caso no S1 e S3, com RHS respectivo de 800 e 750, logo S3 sai, com isso devemos tornar a posição
# da linha S3 e coluna X11 apenas has "1" na em S3,X11 e o resto da coluna seja 0. Com isso, temos que subtrair a linha 1 (ou 0 dado python) e 2 pela coluna 4.

A1 = copy(A)
A1[0] = A[0]-2*A[3]
A1[1] = A[1]-A[3]

print('A1:')
print(A1)



A:
[[   2    2    2    2    2    2    0    0    0    0    0 4000]
 [   1    1    1    0    0    0    1    0    0    0    0  800]
 [   0    0    0    1    1    1    0    1    0    0    0 1200]
 [   1    0    0    1    0    0    0    0    1    0    0  750]
 [   0    1    0    0    1    0    0    0    0    1    0  920]
 [   0    0    1    0    0    1    0    0    0    0    1  330]]
----------------------------------------------------------------
A1:
[[   0    2    2    0    2    2    0    0   -2    0    0 2500]
 [   0    1    1   -1    0    0    1    0   -1    0    0   50]
 [   0    0    0    1    1    1    0    1    0    0    0 1200]
 [   1    0    0    1    0    0    0    0    1    0    0  750]
 [   0    1    0    0    1    0    0    0    0    1    0  920]
 [   0    0    1    0    0    1    0    0    0    0    1  330]]


In [159]:
#2° iteração

# Ordem das colunas da tabela: X11, X12, X12, X21, X22, X23, S1, S2, S3, S4, S5, RHS
# Ordem das linhas da tabela: X0, S1, S2, X11, S4, S5

print('A1:')
print(A1)
print('----------------------------------------------------------------')
# Agora, vamos para a próxima coluna, a X12. Mesmo processo anteriormente. Na coluna do X12, apenas o S1 e S4 podem dividir seus RHS, dando respectivamente RHS1/S1 = 50 e RHS4/S4 = 920, logo S1 sai da base.

A2 = copy(A1)

A2[0] = A1[0] - 2*A1[1]
A2[4] = A1[4] - A1[1]

print('A2:')
print(A2)



A1:
[[   0    2    2    0    2    2    0    0   -2    0    0 2500]
 [   0    1    1   -1    0    0    1    0   -1    0    0   50]
 [   0    0    0    1    1    1    0    1    0    0    0 1200]
 [   1    0    0    1    0    0    0    0    1    0    0  750]
 [   0    1    0    0    1    0    0    0    0    1    0  920]
 [   0    0    1    0    0    1    0    0    0    0    1  330]]
----------------------------------------------------------------
A2:
[[   0    0    0    2    2    2   -2    0    0    0    0 2400]
 [   0    1    1   -1    0    0    1    0   -1    0    0   50]
 [   0    0    0    1    1    1    0    1    0    0    0 1200]
 [   1    0    0    1    0    0    0    0    1    0    0  750]
 [   0    0   -1    1    1    0   -1    0    1    1    0  870]
 [   0    0    1    0    0    1    0    0    0    0    1  330]]


In [160]:
#3° iteração

# Ordem das colunas da tabela: X11, X12, X12, X21, X22, X23, S1, S2, S3, S4, S5, RHS
# Ordem das linhas da tabela: X0, X12, S2, X11, S4, S5

print('A2:')
print(A2)
print('----------------------------------------------------------------')

#Prosseguindo, agora para a coluna do X21, isto dado que na coluna X0, o X13 foi zerada anteriormente, então pula para a próxima não zerada. Nas linhas desta coluna
#Na coluna do X21, X12 é negativo então não conta, porém S2, X11 e S4 = 1.
#Fazendo RHS/X&S temos S2 -> 1200, X11 -> 750 e S4 -> 870, logo X11 sai.

A3 = copy(A2)
A3[0] = A2[0] - 2*A2[3]
A3[1] = A2[1] + A2[3]
A3[2] = A2[2] - A2[3]
A3[4] = A2[4] - A2[3]

print('A3:')
print(A3)



A2:
[[   0    0    0    2    2    2   -2    0    0    0    0 2400]
 [   0    1    1   -1    0    0    1    0   -1    0    0   50]
 [   0    0    0    1    1    1    0    1    0    0    0 1200]
 [   1    0    0    1    0    0    0    0    1    0    0  750]
 [   0    0   -1    1    1    0   -1    0    1    1    0  870]
 [   0    0    1    0    0    1    0    0    0    0    1  330]]
----------------------------------------------------------------
A3:
[[ -2   0   0   0   2   2  -2   0  -2   0   0 900]
 [  1   1   1   0   0   0   1   0   0   0   0 800]
 [ -1   0   0   0   1   1   0   1  -1   0   0 450]
 [  1   0   0   1   0   0   0   0   1   0   0 750]
 [ -1   0  -1   0   1   0  -1   0   0   1   0 120]
 [  0   0   1   0   0   1   0   0   0   0   1 330]]


In [161]:
#4° iteração

# Ordem das colunas da tabela: X11, X12, X12, X21, X22, X23, S1, S2, S3, S4, S5, RHS
# Ordem das linhas da tabela: X0, X12, S2, X21, S4, S5

print('A3:')
print(A3)
print('----------------------------------------------------------------')

# Na coluna X0, o próximo valor > 0 é o X22, candidato a entrar.
# Na sua coluna, S2 e S4 são candidatos a sair, S2 -> 450 e S4 -> 120, logo S4 sai.

A4 = copy(A3)
A4[0] = A3[0] - 2*A3[4]
A4[2] = A3[2] - A3[4]

print('A4:')
print(A4)



A3:
[[ -2   0   0   0   2   2  -2   0  -2   0   0 900]
 [  1   1   1   0   0   0   1   0   0   0   0 800]
 [ -1   0   0   0   1   1   0   1  -1   0   0 450]
 [  1   0   0   1   0   0   0   0   1   0   0 750]
 [ -1   0  -1   0   1   0  -1   0   0   1   0 120]
 [  0   0   1   0   0   1   0   0   0   0   1 330]]
----------------------------------------------------------------
A4:
[[  0   0   2   0   0   2   0   0  -2  -2   0 660]
 [  1   1   1   0   0   0   1   0   0   0   0 800]
 [  0   0   1   0   0   1   1   1  -1  -1   0 330]
 [  1   0   0   1   0   0   0   0   1   0   0 750]
 [ -1   0  -1   0   1   0  -1   0   0   1   0 120]
 [  0   0   1   0   0   1   0   0   0   0   1 330]]


In [162]:
#5° iteração

# Ordem das colunas da tabela: X11, X12, X12, X21, X22, X23, S1, S2, S3, S4, S5, RHS
# Ordem das linhas da tabela: X0, X12, S2, X21, X22, S5

print('A4:')
print(A4)
print('----------------------------------------------------------------')

# O X13, agora não é mais 0, mas > 0, logo ele é o próximo candidato a entrar.
# Em sua coluna, candidatos a sair são X12, S2 e S5.
# X12 -> 800, S2 -> 330 e S5 -> 330, neste caso S2 = S5, mas vamos com o primeiro que apareçe, S2 sai.

A5 = copy(A4)

A5[0] = A4[0] - 2*A4[2]
A5[1] = A4[1] - A4[2]
A5[4] = A4[4] + A4[2]
A5[5] = A4[5] - A4[2]

print('A5:')
print(A5)



A4:
[[  0   0   2   0   0   2   0   0  -2  -2   0 660]
 [  1   1   1   0   0   0   1   0   0   0   0 800]
 [  0   0   1   0   0   1   1   1  -1  -1   0 330]
 [  1   0   0   1   0   0   0   0   1   0   0 750]
 [ -1   0  -1   0   1   0  -1   0   0   1   0 120]
 [  0   0   1   0   0   1   0   0   0   0   1 330]]
----------------------------------------------------------------
A5:
[[  0   0   0   0   0   0  -2  -2   0   0   0   0]
 [  1   1   0   0   0  -1   0  -1   1   1   0 470]
 [  0   0   1   0   0   1   1   1  -1  -1   0 330]
 [  1   0   0   1   0   0   0   0   1   0   0 750]
 [ -1   0   0   0   1   1   0   1  -1   0   0 450]
 [  0   0   0   0   0   0  -1  -1   1   1   1   0]]


In [172]:
# Na linha X0, todos estão <= 0, logo está na solução ótima.

# Agora que sabemos quanto cada Xnm vai armazenar, precisamos saber quanto custará.
# Basta multiplicar qunato será armazenado pelo seu custo (cn).

print('cn:')
print('x11 x12 x13 x21 x22 x23')
print(cn)

# Neste caso, o armazenamento será:

print('x11 =', 0)
print('x12 =', A5[1][11])
print('x13 =', A5[2][11])
print('x21 =', A5[3][11])
print('x22 =', A5[4][11])
print('x23 =', 0)

r = ([0, A5[1][11], A5[2][11], A5[3][11], A5[4][11], 0])
r = array(r)
print('r:', r)

print('O custo total, multiplicando a matriz de armazenmaneto com a de custos, temos r*cn:', dot(r,cn), '. Isso sendo a solução ótima do problema.')


cn:
x11 x12 x13 x21 x22 x23
[15 10  8 13  9 20]
x11 = 0
x12 = 470
x13 = 330
x21 = 750
x22 = 450
x23 = 0
r: [  0 470 330 750 450   0]
O custo total, multiplicando a matriz de armazenmaneto com a de custos, temos r*cn: 21140 . Isso sendo a solução ótima do problema.
