# LabPython - ERMAC/2025 (OFICIAL) - 01/25
## Bernardo T Schettini - 154235 - FURG

## Imports & Defs

In [1]:
import numpy as np
import sympy as sp
from sympy import symbols



In [27]:
mensagem = ("Isto é um exemplo do 'print'.")
print(mensagem)

Isto é um exemplo do 'print'.


In [15]:
def array(I):

  return np.array(I)

def dot(u,v):

    return np.dot(u,v)

#def max(A):
    #return np.max(A)

#def mean(A):
    #return np.mean(A)

def somaC(matriz):
    return np.sum(matriz, axis=0)

def somaL(matriz):
    return np.sum(matriz, axis=1)

# Definida as matrizes de comparação, o vetor de prioridade relativa é determinado por um auto
# vetor que viabilizará a determinação do grau de importância dos elementos em cada nível
# hierárquico, sendo esta a fase de priorização dos elementos do sistema.

#NC = Normalizar coluna
#MN = Matriz Normalizada

def NC(M):
    # Calcula a soma de cada coluna
    soma_colunas = somaC(M)
    
    # Divide cada elemento da coluna pela soma da coluna correspondente
    matriz_normalizada = M / soma_colunas
    
    return matriz_normalizada

def round(a,n):
    return np.round(a,n)


def append(X, a):

    return np.append(X,a)

def reshape(a,i,j):
    return a.reshape(i,j)


## Critérios & Subcritérios

In [ ]:
# Critérios: 
# 1 -> Conhecimentos técnicos
# 2 -> Competência comportamental (avaliada por meio de entrevista)


# Subcritérios:
# 1 -> Experiência anterior em projetos de pesquisa
# 2 -> Conhecimento em ferramentas do projeto: linguagem Python e os ambientes de desenvolvimento (IDEs)
# 3 -> Motivação/interesse
# 4 -> Disponibilidade de tempo (comprovante de matrícula)
# 5 -> Desenvoltura social



# 1 -> Conhecimentos técnicos
# 1.1 -> Experiência anterior em projetos de pesquisa
# 1.2 -> Conhecimento em ferramentas do projeto: linguagem Python e os ambientes de desenvolvimento (IDEs)



# 2 -> Competência comportamental (avaliada por meio de entrevista)
# 2.1 -> Motivação/interesse
# 2.2 -> Disponibilidade de tempo (comprovante de matrícula)
# 2.3 -> Desenvoltura social




## Resultados

### Peso subcriterios

In [4]:
#ordem dos criterios preferiveis: 3,5,2,1,4

M = ([1  , 1/3, 1/8, 5, 1/7],
     [3  , 1  , 1/5, 7, 1/3],
     [8  , 5  , 1  , 9, 3  ],
     [1/5, 1/7, 1/9, 1, 1/7],
     [7  , 3  , 1/3, 7, 1  ])

M = array(M)

MN = NC(M)

MM = somaL(MN)/5



#preferencia de apenas os subcriterios
MM

#somando subcriterios para encontrar preferencia de seus criterios
y1 = MM[0] + MM[1]
y2 = MM[2] + MM[3] + MM[4]

#preferencia dos criterios 
MR = [y1, y2]
#print(y1,y2)

#preferencia dos criterios e subcriterios
MR = append(MR, MM)
#print(MR, MR[0]+MR[1], MR[2]+MR[3]+MR[4])
#print(MR.shape)

#print(MR)
print(MM)


[0.0722489  0.13767034 0.49385667 0.0307394  0.26548469]


### Resultados errados

In [50]:
#Testes com candidatos - com criterios


C1 = [5, 9, 10, 5, 9, 10, 9]
C2 = [0, 8, 10, 0, 8, 10, 8]
C3 = [5, 10, 10, 5, 10, 10, 10]
C4 = [5, 8, 0, 5, 8, 10, 8]
C5 = [0, 10, 10, 0, 10, 10, 10]

print(dot(C1,MR), dot(C2,MR), dot(C3,MR), dot(C4,MR), dot(C5,MR))

16.411218198281173 12.822436396562345 17.874759279322816 14.352992105286832 15.749518558645633


In [48]:
#print(dot(Cs1,MM), dot(Cs2,MM), dot(Cs3,MM), dot(Cs4,MM), dot(Cs5,MM))
print(dot(C1,MMR), dot(C2,MMR), dot(C3,MMR), dot(C4,MMR), dot(C5,MMR))

14.41124757612803 10.495509917281131 15.588925625090308 12.504180765238624 12.850866015205682


In [63]:
# Testes candidatos 2 - sem critérios (somente subcritérios)

Cs1 = [10, 5, 9, 10, 9]
Cs2 = [10, 0, 8, 10, 8]
Cs3 = [10, 5, 10, 10, 10]
Cs4 = [0, 5, 8, 10, 8]
Cs5 = [10, 0, 10, 10, 10]


print(dot(Cs1,MRx), dot(Cs2,MRx), dot(Cs3,MRx), dot(Cs4,MRx), dot(Cs5,MRx))
print(dot(Cs1,MM), dot(Cs2,MM), dot(Cs3,MM), dot(Cs4,MM), dot(Cs5,MM))

8.380251488942585 6.76050297788517 9.086050892649583 7.0797670732828895 8.172101785299166
1.631612492197974 6.316124921979737 8.81331738553947 6.773418774513137 7.6266347710789395


### Testes

In [71]:
# Testes de verificação de código

MT = ([1, 1/7, 1/3, 1/2],
     [7, 1, 5, 5],
     [3, 1/5, 1, 3],
     [2, 1/5, 1/3, 1])


MT = array(M1)

MNT = NC(M1)

MMT = somaL(MN1)/4

MMT




array([0.06803681, 0.61573137, 0.20654708, 0.10968474])

### Peso candidatos

In [4]:
#time to fix things

#MM peso subcriterios

#pontuação realzada pelas professoras
p1 = [10, 5, 9 , 10, 9 ]
p2 = [10, 0, 8 , 10, 8 ]
p3 = [10, 5, 10, 10, 10]
p4 = [0 , 5, 8 , 10, 8 ] 
p5 = [10, 0, 10, 10, 10]

#atravez disso devemos fazer uma comparação para a par deles a cada subcriterio

#obs: p3 DEVE ser o melhor candidato
#ordem de resultados: p3, p1, p5, p4, p2

#subcriterio 1 - Experiência anterior em projetos de pesquisa
M1 = ([1  , 3  , 1/3, 3, 3  ],
      [1/3, 1  , 1/3, 3, 1/3],
      [3  , 3  , 1  , 9, 3  ],
      [1/3, 1/3, 1/9, 1, 1/3],
      [1/3, 3  , 1/3, 3, 1  ])


M1 = array(M1)

MN1 = NC(M1)

MM1 = somaL(MN1)/5

print(sum(MM1))
print(MM1)
MM1.shape




1.0
[0.23948328 0.10454172 0.44579907 0.04953323 0.1606427 ]


(5,)

In [5]:
#subcriterio 2 - Competência comportamental (avaliada por meio de entrevista)

#obs: p3 DEVE ser o melhor candidato
#ordem de resultados: p3, p1, p5, p4, p2


p1 = [5, 9 , 10, 9 ]
p2 = [0, 8 , 10, 8 ]
p3 = [5, 10, 10, 10]
p4 = [5, 8 , 10, 8 ] 
p5 = [0, 10, 10, 10]

M2 = ([  1 , 9  , 1/3, 3  ,  9  ],
      [ 1/9, 1  , 1/9, 1/9,  1/3],
      [ 3  , 9  , 1  , 3  ,  9  ],
      [ 1/3, 9  , 1/3, 1  ,  9  ],
      [ 1/9, 3  , 1/9, 1/9,  1  ])

M2 = array(M2)

MN2 = NC(M2)

MM2 = somaL(MN2)/5
#MM2 = reshape(MM2,5,1)

print(sum(MM2))
print(MM2)
MM2.shape



1.0
[0.28386741 0.02852423 0.44226052 0.1992145  0.04613334]


(5,)

In [6]:
#subcriterio 3 - Motivação/interesse

p1 = [9 , 10, 9 ]
p2 = [8 , 10, 8 ]
p3 = [10, 10, 10]
p4 = [8 , 10, 8 ] 
p5 = [10, 10, 10]

#obs: p3 DEVE ser o melhor candidato
#ordem de resultados: p3, p1, p5, p4, p2

M3 = ([1  , 3, 1/3, 3  , 3  ],
      [1/3, 1, 1/3, 1/3, 1/3],
      [3  , 3, 1  , 3  , 3  ],
      [1/3, 3, 1/3, 1  , 1/3],
      [1/3, 3, 1/3, 3  , 1  ])

M3 = array(M3)

MN3 = NC(M3)

MM3 = somaL(MN3)/5

print(sum(MM3))
print(MM3)
MM3.shape

1.0
[0.25105066 0.07243664 0.38819352 0.1161091  0.17221008]


(5,)

In [7]:
#subcriterio 4 - Disponibilidade de tempo (comprovante de matrícula)

p1 = [10, 9 ]
p2 = [10, 8 ]
p3 = [10, 10]
p4 = [10, 8 ] 
p5 = [10, 10]

#obs: p3 DEVE ser o melhor candidato
#ordem de resultados: p3, p1, p5, p4, p2

M4 = ([1  , 3, 1/3, 3  , 3  ],
      [1/3, 1, 1/3, 1/3, 1/3],
      [3  , 3, 1  , 3  , 3  ],
      [1/3, 3, 1/3, 1  , 1/3],
      [1/3, 3, 1/3, 3  , 1  ])

M4 = array(M4)

MN4 = NC(M4)

MM4 = somaL(MN4)/5

print(sum(MM4))
print(MM4)
MM4.shape

1.0
[0.25105066 0.07243664 0.38819352 0.1161091  0.17221008]


(5,)

In [8]:
#subcriterio 5 - Desenvoltura social

p1 = [9 ]
p2 = [8 ]
p3 = [10]
p4 = [8 ] 
p5 = [10]

#obs: p3 DEVE ser o melhor candidato
#ordem de resultados: p3, p1, p5, p4, p2

M5 = ([1  , 3, 1/3, 3  , 1/3],
      [1/3, 1, 1/4, 1/3, 1/4],
      [3  , 4, 1  , 4  , 3  ],
      [1/3, 3, 1/4, 1  , 1/4],
      [3  , 4, 1/3, 4  , 1  ]) 

M5 = array(M5)

MN5 = NC(M5)

MM5 = somaL(MN5)/5

print(sum(MM5))
print(MM5)
MM5.shape

1.0
[0.15929794 0.06085614 0.41290469 0.09833362 0.26860761]


(5,)

In [9]:
# matriz de priioridade, com os vetores de preferencia dos candidatos a cada subcriterio

c = np.column_stack((MM1, MM2, MM3, MM4, MM5))
print(c)
c.shape

[[0.23948328 0.28386741 0.25105066 0.25105066 0.15929794]
 [0.10454172 0.02852423 0.07243664 0.07243664 0.06085614]
 [0.44579907 0.44226052 0.38819352 0.38819352 0.41290469]
 [0.04953323 0.1992145  0.1161091  0.1161091  0.09833362]
 [0.1606427  0.04613334 0.17221008 0.17221008 0.26860761]]


(5, 5)

In [10]:
# Resultado: matriz dos candidatos x peso dos subcriterios

R = dot(c,MM)
print(R)
sum(R)

[0.23037388 0.06563632 0.40635932 0.1180211  0.17960939]


1.0

In [11]:
#Resultados

print(MM)

print(R)

[0.0722489  0.13767034 0.49385667 0.0307394  0.26548469]
[0.23037388 0.06563632 0.40635932 0.1180211  0.17960939]


### Coerencia

In [12]:
#Determinar coerencia dos resultados

#1) Determinar o lambda máximo, considera-se o n° de subcritérios, que neste caso são 5. Divide-se o vetor do preferência (MRx) de entradas pelo vector da Média (MM) e obtêm-se um novo
# vetor. Deste vetor resultante, somam-se as suas parcelas e divide-se pelo n° de subcritérios (5), que resulta no lambda máximo:

lmax = sum(dot(M,MM)/MM)/5
lmax




5.479322762571299

In [13]:
#Calcular o indice de coerencia IC (CI): (lmax - n)/(n - 1)

CI = (lmax-5)/(5-1)
CI

0.11983069064282481

In [14]:
# Comparar indice de coerencia IC ao indice aleatorio IA, e verificar se <= 0.1 (10%), para n=5, IA= 1,12

IA = 1.12
RC = CI/IA
RC

0.10699168807395071

In [47]:
# Como RC <= .1 então a resposta é coerente