# TCC
# Uso de AHP e Python na decisão de local de construção de novo quartel de bombeiros militares em Rio Grande, RS
### 04/2025


# Imports & Defs

In [2]:
import numpy as np
import sympy as sp
from sympy import symbols

In [3]:
def array(I):

  return np.array(I)

def dot(u,v):

    return np.dot(u,v)

def max(A):
    return np.max(A)

def mean(A):
    return np.mean(A)

def somaC(matriz):
    return np.sum(matriz, axis=0)

def somaL(matriz):
    return np.sum(matriz, axis=1)

# Definida as matrizes de comparação, o vetor de prioridade relativa é determinado por um auto
# vetor que viabilizará a determinação do grau de importância dos elementos em cada nível
# hierárquico, sendo esta a fase de priorização dos elementos do sistema.

#NC = Normalizar coluna
#MN = Matriz Normalizada

def NC(M):
    # Calcula a soma de cada coluna
    soma_colunas = somaC(M)
    
    # Divide cada elemento da coluna pela soma da coluna correspondente
    matriz_normalizada = M / soma_colunas
    
    return matriz_normalizada

def round(a,n):
    return np.round(a,n)


def append(X, a):

    return np.append(X,a)


# Divisao do município

In [4]:
# 5 distritos:
# D1) Rio Grande: D1.1) Porto Novo, D1.2) Central, D1.3) Cassino,
# D1.4) Lagoa, D1.5) Oeste Orla, D1.6) Avenida Itália, D1.7) Portuária Industrial,
# D1.8) Bolaxa, D1.9) Senandes, D1.10) Carreiros, D1.11) Jardim do Sol,
# D1.12) Parque Marinha, D1.13) Parque São Pedro;
# D2) Ilha dos Marinheiros: Vila do Porto do Rei, Ilha dos marineheiros, ilhas Leonídio, das Pombas, da Pólvora, dos Cavalos, da Constância, das Cabras, do Caldeirão e da Cascuda ;
# D3) Povo Novo: Vila do Povo Novo, ilhas da Torotoma, dos Mosquitos, dos Carneiros, Martin Coelho e do Malandro;
# D5) Taim: Vila do Taim, abrangendo as ilhas Pequena, Grande e Sangradouro.


# Áreas afetadas pelas enchentes: Rio Grande e Ilha dos Marinehiros
# Rio Grande: Zona porto novo, central, lagoa, oeste orla, avenida itália, portuária industrial
# Ilha dos marinheiros: Distrito ilhas


# Critérios:
#C1) Frequênica: É direcionada ao fluxo das solicitações de emergência e urgência;
#C2) Infraestrutura: As condições de acesso e mobilidade às demais áreas da cidade;
#C3) Desenvolvimento: Fator do desenvolvimento econômico e social da cidade.

# Subcritérios:

#C1.1) Tempo de resposta; C1.2) Número de ocorrências; C1.3) Grau de importância.
#C2.1) Unidade de saúde; C2.2) Distância ou acesso; C2.3) Risco de atuação; C2.4) Risco de enchente.
#C3.1) Comercial; C3.2) Residdencial; C3.3) Rural; C3.4) Industrial; C3.5) Poder aquisitivo da população.

# Dados



## N° de Ocorrências (Distritos)

In [36]:
# Dn = Distrito n°

D1 = 33605
D2 = 54
D3 = 114
D4 = 37
D5 = 367

D = [D1,D2,D3,D4,D5]
D

[33605, 54, 114, 37, 367]

In [38]:
# Si = Sessão i°


S1 = 26
S2 = 1202
S3 = 1866
S4 = 1049
S5 = 159
S6 = 501
S7 = 245
S8 = 258
S9 = 127
S10 = 281
S11 = 196
S12 = 360
S13 = 266

S = [S1,S2,S3,S4,S5,S6,S7,S8,S9,S10,S11,S12,S13]
S

[26, 1202, 1866, 1049, 159, 501, 245, 258, 127, 281, 196, 360, 266]

# AHP

## Comparação dos subcritérios, escolher os mais relevantes

### Criterio 1

In [3]:
#Criterio 1: Frequencia
#1.1- Tempo de resposta
#1.2- N de ocorrência
#1.3- grau de importancia

C1 = ([1  , 9,   2],
      [1/9, 1, 1/9],
      [1/2, 9,   1])

C1=array(C1)

C1.shape
C1



array([[1.        , 9.        , 2.        ],
       [0.11111111, 1.        , 0.11111111],
       [0.5       , 9.        , 1.        ]])

In [4]:
# Normalização

C1N = NC(C1)
C1N

array([[0.62068966, 0.47368421, 0.64285714],
       [0.06896552, 0.05263158, 0.03571429],
       [0.31034483, 0.47368421, 0.32142857]])

In [5]:
#Vetor media/prioridade

VM1 = somaL(C1N)/3
print(sum(VM1))
print(VM1)
VM1.shape

VM1*100

1.0
[0.579077   0.05243713 0.36848587]


array([57.90770029,  5.24371273, 36.84858698])

In [8]:
# Teste de consistencia

lmax = sum(dot(C1,VM1)/VM1)/3
CI = (lmax-3)/(3-1)
IA = .58
CR = CI/IA
print(CR)

0.04654082568249392


In [9]:
#Calcular o indice de coerencia IC (CI): (lmax - n)/(n - 1)


#1) Determinar o lambda máximo, considera-se o n° de subcritérios. Divide-se o vetor do preferência de entradas (Mx) pelo vector da Média (MMx) e obtêm-se um novo vetor -> lmax = sum(dot(Mx,MM)/MM)/n.
# Deste vetor resultante, somam-se as suas parcelas e divide-se pelo n° de subcritérios, que resulta no lambda máximo:

CI = (lmax-3)/(3-1)
CI

np.float64(0.026993678895846474)

In [10]:
# Comparar indice de coerencia IC ao indice aleatorio IA, e verificar se RC <= 0.1 (10%)

IA = .58
RC = CI/IA
print(RC)

0.04654082568249392


### Criterio 2

In [14]:
#Criterio 2: Infraestrutura
#2.1- Unidade de saúde
#2.2- Distancia/acesso
#2.3- Risco para corporação

C2 = ([1, 1/9,   1/9],
      [9,   1,   1/2],
      [9,   2,     1])

C2=array(C2)

C2.shape
C2

array([[1.        , 0.11111111, 0.11111111],
       [9.        , 1.        , 0.5       ],
       [9.        , 2.        , 1.        ]])

In [15]:
# Normalização

C2N = NC(C2)
C2N

array([[0.05263158, 0.03571429, 0.06896552],
       [0.47368421, 0.32142857, 0.31034483],
       [0.47368421, 0.64285714, 0.62068966]])

In [16]:
# Vetor media
VM2 = somaL(C2N)/3
VM2*100


array([ 5.24371273, 36.84858698, 57.90770029])

In [77]:
# Teste de consistencia
#1) Determinar o lambda máximo, considera-se o n° de subcritérios. Divide-se o vetor do preferência de entradas (Mx) pelo vector da Média (MMx) e obtêm-se um novo vetor -> lmax = sum(dot(Mx,MM)/MM)/n.
# Deste vetor resultante, somam-se as suas parcelas e divide-se pelo n° de subcritérios, que resulta no lambda máximo:


lmax = sum(dot(C2,VM2)/VM2)/3
lmax

np.float64(3.0539873577916925)

In [78]:
#Calcular o indice de coerencia IC (CI): (lmax - n)/(n - 1)

CI = (lmax-3)/(3-1)
CI

np.float64(0.02699367889584625)

In [79]:
# Comparar indice de coerencia IC ao indice aleatorio IA, e verificar se RC <= 0.1 (10%)

IA = .58
RC = CI/IA
RC

np.float64(0.04654082568249354)

### Criterio 3

In [17]:
#Criterio 3: Desenvolvimento
#3.1- Comercial
#3.2- Residencial
#3.3- Rural
#3.4- Industrial
#3.5- Poder aquisitivo


C3 = ([1,   6  , 9 , 9, 1/2],
      [1/6, 1  , 3 , 3, 1/2],
      [1/9, 1/3, 1 , 1, 1/3],
      [1/9, 1/3, 1 , 1, 1/3],
      [2  ,   2, 3 , 3,   1])

C3=array(C3)

C3.shape
C3

array([[1.        , 6.        , 9.        , 9.        , 0.5       ],
       [0.16666667, 1.        , 3.        , 3.        , 0.5       ],
       [0.11111111, 0.33333333, 1.        , 1.        , 0.33333333],
       [0.11111111, 0.33333333, 1.        , 1.        , 0.33333333],
       [2.        , 2.        , 3.        , 3.        , 1.        ]])

In [18]:
# Normalização

C3N = NC(C3)
C3N

array([[0.29508197, 0.62068966, 0.52941176, 0.52941176, 0.1875    ],
       [0.04918033, 0.10344828, 0.17647059, 0.17647059, 0.1875    ],
       [0.03278689, 0.03448276, 0.05882353, 0.05882353, 0.125     ],
       [0.03278689, 0.03448276, 0.05882353, 0.05882353, 0.125     ],
       [0.59016393, 0.20689655, 0.17647059, 0.17647059, 0.375     ]])

In [19]:
# Vetor media
VM3 = somaL(C3N)/5
VM3*100

array([43.24190304, 13.8613956 ,  6.19833405,  6.19833405, 30.50003325])

In [21]:
# Teste de consistencia
#1) Determinar o lambda máximo, considera-se o n° de subcritérios. Divide-se o vetor do preferência de entradas (Mx) pelo vector da Média (MMx) e obtêm-se um novo vetor -> lmax = sum(dot(Mx,MM)/MM)/n.
# Deste vetor resultante, somam-se as suas parcelas e divide-se pelo n° de subcritérios, que resulta no lambda máximo:


lmax = sum(dot(C3,VM3)/VM3)/5
lmax

np.float64(5.488937213268254)

In [22]:
#Calcular o indice de coerencia IC (CI): (lmax - n)/(n - 1)

CI = (lmax-5)/(5-1)
CI

np.float64(0.12223430331706342)

In [23]:
# Comparar indice de coerencia IC ao indice aleatorio IA, e verificar se RC <= 0.1 (10%)

IA = 1.12
RC = CI/IA
RC

np.float64(0.10913777081880661)

## Comparação dos Distritos

In [9]:
# distritos:
# Rio grande
# ilha dos marinheiros
# povo novo
# taim
# vila da quinta


D = ([1  , 9,   8,    7,   8],
     [1/9, 1, 1/4,    1, 1/2],
     [1/8, 4,   1,    3,   1],
     [1/7, 1, 1/3,    1,   2],
     [1/8, 2,   1,  1/2,   1])

D = array(D)
D


array([[1.        , 9.        , 8.        , 7.        , 8.        ],
       [0.11111111, 1.        , 0.25      , 1.        , 0.5       ],
       [0.125     , 4.        , 1.        , 3.        , 1.        ],
       [0.14285714, 1.        , 0.33333333, 1.        , 2.        ],
       [0.125     , 2.        , 1.        , 0.5       , 1.        ]])

In [10]:
# Normalização

DN = NC(D)
DN

array([[0.66490765, 0.52941176, 0.75590551, 0.56      , 0.64      ],
       [0.07387863, 0.05882353, 0.02362205, 0.08      , 0.04      ],
       [0.08311346, 0.23529412, 0.09448819, 0.24      , 0.08      ],
       [0.09498681, 0.05882353, 0.03149606, 0.08      , 0.16      ],
       [0.08311346, 0.11764706, 0.09448819, 0.04      , 0.08      ]])

In [11]:
# Vetor media/prioridade
DM = somaL(DN)/5
print(DM)
DM*100

[0.63004499 0.05526484 0.14657915 0.08506128 0.08304974]


array([63.00449856,  5.52648409, 14.65791526,  8.506128  ,  8.30497409])

In [12]:
# Teste de consistencia
#1) Determinar o lambda máximo, considera-se o n° de subcritérios. Divide-se o vetor do preferência de entradas (Mx) pelo vector da Média (MMx) e obtêm-se um novo vetor -> lmax = sum(dot(Mx,MM)/MM)/n.
# Deste vetor resultante, somam-se as suas parcelas e divide-se pelo n° de subcritérios, que resulta no lambda máximo:


lmax = sum(dot(D,DM)/DM)/5
lmax

np.float64(5.402934428887714)

In [13]:
#Calcular o indice de coerencia IC (CI): (lmax - n)/(n - 1)

CI = (lmax-5)/(5-1)
CI

np.float64(0.10073360722192848)

In [14]:
# Comparar indice de coerencia IC ao indice aleatorio IA, e verificar se RC <= 0.1 (10%)

IA = 1.12
RC = CI/IA
RC

np.float64(0.0899407207338647)

In [17]:
#Teste de consistência
lmax = sum(dot(D,DM)/DM)/5
CI = (lmax-5)/(5-1)
IA = 1.12
CR = CI/IA
CR

np.float64(0.0899407207338647)

## Comparação das Zonas

In [18]:
#Zonas:
# porto novo, central, cassino, lagoa, oeste orla, avenida italia, zona industrial, bolaxa, senandes, carreiros, jardin do sol, parque marinha, parque sao pedro

Z = np.array([
    [1  , 1/4, 1/3, 1/3, 1  , 1/4, 2  , 4  , 4  , 1/2, 5  , 3  , 3  ],
    [4  , 1  , 1  , 5 ,  6  , 6  , 6  , 9  , 9  , 3  , 8  , 9  , 9  ],
    [3  , 1  , 1  , 6  , 6  , 6  , 4  , 9  , 9  , 4  , 8  , 9  , 9  ],
    [3  , 1/5, 1/6, 1  , 1  , 8  , 1  , 8  , 8  , 1  , 4  , 5  , 5  ],
    [1  , 1/6, 1/6, 1  , 1  , 8  , 2  , 4  , 4  , 1  , 3  , 3  , 3  ],
    [4  , 1/6, 1/6, 1/8, 1/8, 1  , 1  , 3  , 3  , 1/7, 4  , 2  , 2  ],
    [1/2, 1/6, 1/4, 1  , 1/2, 1  , 1  , 2  , 2  , 1/3, 3  , 2  , 2  ],
    [1/4, 1/9, 1/9, 1/8, 1/4, 1/3, 1/2, 1  , 1  , 1/8, 3  , 2  , 2  ],
    [1/4, 1/9, 1/9, 1/8, 1/4, 1/3, 1/2, 1  , 1  , 1/8, 2  , 1/2, 1/2],
    [2  , 1/3, 1/4, 1  , 1  , 7  , 3  , 8  , 8  , 1  , 8  , 8  , 8  ],
    [1/5, 1/8, 1/8, 1/4, 1/3, 1/4, 1/3, 1/3, 1/2, 1/8, 1  , 1/2, 1/2],
    [1/3, 1/9, 1/9, 1/5, 1/3, 1/2, 1/2, 1/2, 2  , 1/8, 2  , 1  , 1  ],
    [1/3, 1/9, 1/9, 1/5, 1/3, 1/2, 1/2, 1/2, 2  , 1/8, 2  , 1  , 1  ]
])

Z

array([[1.        , 0.25      , 0.33333333, 0.33333333, 1.        ,
        0.25      , 2.        , 4.        , 4.        , 0.5       ,
        5.        , 3.        , 3.        ],
       [4.        , 1.        , 1.        , 5.        , 6.        ,
        6.        , 6.        , 9.        , 9.        , 3.        ,
        8.        , 9.        , 9.        ],
       [3.        , 1.        , 1.        , 6.        , 6.        ,
        6.        , 4.        , 9.        , 9.        , 4.        ,
        8.        , 9.        , 9.        ],
       [3.        , 0.2       , 0.16666667, 1.        , 1.        ,
        8.        , 1.        , 8.        , 8.        , 1.        ,
        4.        , 5.        , 5.        ],
       [1.        , 0.16666667, 0.16666667, 1.        , 1.        ,
        8.        , 2.        , 4.        , 4.        , 1.        ,
        3.        , 3.        , 3.        ],
       [4.        , 0.16666667, 0.16666667, 0.125     , 0.125     ,
        1.        , 1.     

In [19]:
#Normalização
ZN = NC(Z)
ZN

array([[0.05033557, 0.06488825, 0.08540925, 0.02037697, 0.05517241,
        0.00638298, 0.08955224, 0.0794702 , 0.07476636, 0.04309903,
        0.09433962, 0.06521739, 0.06521739],
       [0.20134228, 0.25955299, 0.25622776, 0.30565461, 0.33103448,
        0.15319149, 0.26865672, 0.17880795, 0.1682243 , 0.25859415,
        0.1509434 , 0.19565217, 0.19565217],
       [0.15100671, 0.25955299, 0.25622776, 0.36678553, 0.33103448,
        0.15319149, 0.17910448, 0.17880795, 0.1682243 , 0.3447922 ,
        0.1509434 , 0.19565217, 0.19565217],
       [0.15100671, 0.0519106 , 0.04270463, 0.06113092, 0.05517241,
        0.20425532, 0.04477612, 0.1589404 , 0.14953271, 0.08619805,
        0.0754717 , 0.10869565, 0.10869565],
       [0.05033557, 0.04325883, 0.04270463, 0.06113092, 0.05517241,
        0.20425532, 0.08955224, 0.0794702 , 0.07476636, 0.08619805,
        0.05660377, 0.06521739, 0.06521739],
       [0.20134228, 0.04325883, 0.04270463, 0.00764137, 0.00689655,
        0.02553191, 0.04477

In [20]:
# Vetor medio/prioridade
ZM = somaL(ZN)/13
print(ZM)
ZM*100

[0.06109444 0.22488727 0.22545966 0.09988391 0.07491408 0.05096703
 0.04160923 0.02424002 0.01777192 0.12108011 0.01514398 0.02147418
 0.02147418]


array([ 6.10944354, 22.48872671, 22.54596642,  9.98839131,  7.49140833,
        5.09670257,  4.16092289,  2.4240017 ,  1.77719158, 12.10801141,
        1.51439782,  2.14741785,  2.14741785])

In [22]:
#consistencia

lmax = sum(dot(Z,ZM)/ZM)/13
CI = (lmax-13)/(13-1)
IA = 1.56
CR = CI/IA
CR

np.float64(0.08840546269988442)

## Experimento 1


### subcriterio

In [3]:
# subcritérios: Tempo resposta, risco a coorporação e comercial
# zonas: carreiros, lagoa, oeste orla, porto novo, av italia

#comparação subcritérios

#comparação par a par
SC = ([1  , 1/2, 9],
      [2  , 1  , 9],
      [1/9, 1/9, 1])

SC = array(SC)
SC


array([[1.        , 0.5       , 9.        ],
       [2.        , 1.        , 9.        ],
       [0.11111111, 0.11111111, 1.        ]])

In [73]:
#normalização
NSC = NC(SC)
NSC

array([[0.32142857, 0.31034483, 0.47368421],
       [0.64285714, 0.62068966, 0.47368421],
       [0.03571429, 0.06896552, 0.05263158]])

In [81]:
#vetor media
SCM = somaL(NSC)/3
SCM*100
SCM

array([0.36848587, 0.579077  , 0.05243713])

In [75]:
#consistencia
lmax = sum(dot(SC,SCM)/SCM)/3
CI = (lmax-3)/(3-1)
IA = .58
RC = CI/IA
RC

np.float64(0.04654082568249392)

### Comparação zonas em relação aos subcriterios

In [62]:
# 1- tempo e resposta
# 2- risco a coorporação
# 3- comercial

#Ordem de zonas: carreiros, lagoa, oeste orla, porto novo, av italia

In [9]:
# 1. tempo e resposta

#comparação par a par
H1 = ([1  , 3  , 6  , 9, 9],
      [1/3, 1  , 3  , 3, 3],
      [1/6, 1/3, 1  , 4, 6],
      [1/9, 1/3, 1/4, 1, 1],
      [1/9, 1/3, 1/6, 1, 1])

 
H1 = array(H1)
#normalização
NH1 = NC(H1)
#media/prioridade
MH1 = somaL(NH1)/5
MH1*100

array([54.13290323, 19.96430108, 15.63326165,  5.21476703,  5.05476703])

In [8]:
#consistencia 

lmax = sum(dot(H1,MH1)/MH1)/5
CI = (lmax-5)/(5-1)
IA = 1.12
RC = CI/IA
RC

np.float64(0.08132723995316515)

In [65]:
# 2. risco a corporação

#comparação par a par
H2 = ([1  , 9  , 9  , 6  , 5  ],
      [1/9, 1  , 1  , 1/3, 1/9],
      [1/9, 1  , 1  , 1/2, 1/8],
      [1/6, 3  , 2  , 1  , 1/6],
      [1/5, 9  , 8  , 6  , 1  ])

H2 = array(H2)

#normalização
NH2 = NC(H2)

#media prioridade
MH2 = somaL(NH2)/5
MH2*100


array([53.27784817,  4.04954686,  4.33389467,  8.57775016, 29.76096014])

In [66]:
#consistencia
lmax = sum(dot(H2,MH2)/MH2)/5
CI = (lmax-5)/(5-1)
IA = 1.12
RC = CI/IA
RC

np.float64(0.0846160062799524)

In [11]:
# 3. comercial

#comparação par a par
H3 = ([1  , 2  , 3  , 9  , 1/4],
      [1/2, 1  , 5  , 8  , 1/5],
      [1/3, 1/5, 1  , 4  , 1/9],
      [1/9, 1/8, 1/4, 1  , 1/9],
      [4  , 5  , 9  , 9  , 1  ])

H3 = array(H3)
H3

array([[1.        , 2.        , 3.        , 9.        , 0.25      ],
       [0.5       , 1.        , 5.        , 8.        , 0.2       ],
       [0.33333333, 0.2       , 1.        , 4.        , 0.11111111],
       [0.11111111, 0.125     , 0.25      , 1.        , 0.11111111],
       [4.        , 5.        , 9.        , 9.        , 1.        ]])

In [13]:
#normalização
NH3 = NC(H3)
NH3

array([[0.1682243 , 0.24024024, 0.16438356, 0.29032258, 0.14950166],
       [0.08411215, 0.12012012, 0.2739726 , 0.25806452, 0.11960133],
       [0.05607477, 0.02402402, 0.05479452, 0.12903226, 0.06644518],
       [0.01869159, 0.01501502, 0.01369863, 0.03225806, 0.06644518],
       [0.6728972 , 0.6006006 , 0.49315068, 0.29032258, 0.59800664]])

In [14]:
#media prioridade
MH3 = somaL(NH3)/5
MH3*100

array([20.25344685, 17.11741435,  6.60741503,  2.92216962, 53.09955414])

In [15]:
#consistencia

lmax = sum(dot(H3,MH3)/MH3)/5
CI = (lmax-5)/(5-1)
IA = 1.12
CR = CI/IA
CR

np.float64(0.09696143273890162)

In [79]:
# matriz prioridade e resultados

#vetor prioridade
SCM

#matriz prioridade
MP = np.column_stack((MH1, MH2, MH3))
print(MP)



[[0.54132903 0.53277848 0.20253447]
 [0.19964301 0.04049547 0.17117414]
 [0.15633262 0.04333895 0.06607415]
 [0.05214767 0.0857775  0.0292217 ]
 [0.05054767 0.2976096  0.53099554]]


In [82]:
#resultado
resultado = dot(MP, SCM)
resultado*100

array([51.86121914, 10.59915034,  8.61676861,  7.041976  , 21.8808859 ])

## Experimento 2

### Subcriterio

In [4]:
# subcritérios: Tempo resposta, grau de importancia, distancia acesso, risco a coorporação e comercial

#comparação subcritérios

#comparação par a par
SC1 =([1  , 9  , 7  , 8  , 6  ],
      [1/9, 1  , 2  , 5  , 2  ],
      [1/7, 1/2, 1  , 3  , 2  ],
      [1/8, 1/5, 1/3, 1  , 1/4],
      [1/6, 1/2, 1/2, 4  , 1  ])

SC1 = array(SC1)
SC1

array([[1.        , 9.        , 7.        , 8.        , 6.        ],
       [0.11111111, 1.        , 2.        , 5.        , 2.        ],
       [0.14285714, 0.5       , 1.        , 3.        , 2.        ],
       [0.125     , 0.2       , 0.33333333, 1.        , 0.25      ],
       [0.16666667, 0.5       , 0.5       , 4.        , 1.        ]])

In [5]:
#Normalização

NSC1 = NC(SC1)
NSC1

array([[0.64698331, 0.80357143, 0.64615385, 0.38095238, 0.53333333],
       [0.07188703, 0.08928571, 0.18461538, 0.23809524, 0.17777778],
       [0.09242619, 0.04464286, 0.09230769, 0.14285714, 0.17777778],
       [0.08087291, 0.01785714, 0.03076923, 0.04761905, 0.02222222],
       [0.10783055, 0.04464286, 0.04615385, 0.19047619, 0.08888889]])

In [6]:
# prioridade/media


SCM1 = somaL(NSC1)/5
SCM1*100
SCM1

array([0.60219886, 0.15233223, 0.11000233, 0.03986811, 0.09559847])

In [7]:
#consistencia
lmax = sum(dot(SC1,SCM1)/SCM1)/5
CI = (lmax-5)/(5-1)
IA = 1.12
RC = CI/IA
RC

np.float64(0.09134255117735872)

### Comparação em relação aos subcritérios

In [35]:
# 1. tempo e resposta
# zonas: carreiros, lagoa, oeste orla, porto novo, av italia


#comparação par a par
A1 = ([1  , 3  , 6  , 9, 9],
      [1/3, 1  , 3  , 3, 3],
      [1/6, 1/3, 1  , 4, 6],
      [1/9, 1/3, 1/4, 1, 1],
      [1/9, 1/3, 1/6, 1, 1])

 
A1 = array(A1)

#normalização
NA1 = NC(A1)

#media/prioridade
MA1 = somaL(NA1)/5
MA1*100

array([54.13290323, 19.96430108, 15.63326165,  5.21476703,  5.05476703])

In [41]:
#consistencia 

lmax = sum(dot(A1,MA1)/MA1)/5
CI = (lmax-5)/(5-1)
IA = 1.12
RC = CI/IA
RC

np.float64(0.08132723995316515)

In [43]:
#2. grau de importancia

#Comparação par a par

A2 = ([1  , 5  , 5  , 2  , 7],
      [1/5, 1  , 1  , 1/3, 4],
      [1/5, 1  , 1  , 1/3, 4],
      [1/2, 3  , 3  , 1  , 5],
      [1/7, 1/4, 1/4, 1/5, 1])

A2 = array(A2)
A2

#normalização
NA2 = NC(A2)
NA2

#media/prioridade
MA2 = somaL(NA2)/5
MA2

array([0.46313899, 0.11394143, 0.11394143, 0.26536741, 0.04361075])

In [44]:
#consistencia
lmax = sum(dot(A2,MA2)/MA2)/5
CI = (lmax-5)/(5-1)
IA = 1.12
RC = CI/IA
RC

np.float64(0.03646576140276188)

In [51]:
#3. distancia/acesso

#Comparação par a par

A3 = ([1, 1/3, 1/3, 1/4, 1/4],
      [3, 1  , 1/2, 2  , 1/3],
      [3, 2  , 1  , 3  , 1/4],
      [4, 1/2, 1/3, 1  , 1/4],
      [4, 3  , 4  , 4  , 1  ])

A3 = array(A3)
A3

#normalização
NA3 = NC(A3)
NA3

#media/prioridade
MA3 = somaL(NA3)/5
MA3

array([0.06277829, 0.1565089 , 0.2135056 , 0.12229049, 0.44491672])

In [52]:
#consistencia
lmax = sum(dot(A3,MA3)/MA3)/5
CI = (lmax-5)/(5-1)
IA = 1.12
RC = CI/IA
RC

np.float64(0.09063291322056802)

In [54]:
# 4. risco a corporação

#comparação par a par
A4 = ([1  , 9  , 9  , 6  , 5  ],
      [1/9, 1  , 1  , 1/3, 1/9],
      [1/9, 1  , 1  , 1/2, 1/8],
      [1/6, 3  , 2  , 1  , 1/6],
      [1/5, 9  , 8  , 6  , 1  ])

A4 = array(A4)

#normalização
NA4 = NC(A4)

#media prioridade
MA4 = somaL(NA4)/5
MA4*100

array([53.27784817,  4.04954686,  4.33389467,  8.57775016, 29.76096014])

In [55]:
#consistencia
lmax = sum(dot(A4,MA4)/MA4)/5
CI = (lmax-5)/(5-1)
IA = 1.12
RC = CI/IA
RC

np.float64(0.0846160062799524)

In [59]:
# 5. comercial

#comparação par a par
A5 = ([1  , 2  , 3  , 9  , 1/4],
      [1/2, 1  , 5  , 8  , 1/5],
      [1/3, 1/5, 1  , 4  , 1/9],
      [1/9, 1/8, 1/4, 1  , 1/9],
      [4  , 5  , 9  , 9  , 1  ])

A5 = array(A5)

#normalização
NA5 = NC(A5)

#media prioridade
MA5 = somaL(NA5)/5
MA5*100

array([20.25344685, 17.11741435,  6.60741503,  2.92216962, 53.09955414])

In [60]:
#consistencia

lmax = sum(dot(A5,MA5)/MA5)/5
CI = (lmax-5)/(5-1)
IA = 1.12
CR = CI/IA
CR

np.float64(0.09696143273890162)

In [64]:
# matriz prioridade e resultados

#vetor prioridade
SCM1

#matriz prioridade
MP1 = np.column_stack((MA1, MA2, MA3, MA4, MA5))
print(MP1)


[[0.54132903 0.46313899 0.06277829 0.53277848 0.20253447]
 [0.19964301 0.11394143 0.1565089  0.04049547 0.17117414]
 [0.15633262 0.11394143 0.2135056  0.04333895 0.06607415]
 [0.05214767 0.26536741 0.12229049 0.0857775  0.0292217 ]
 [0.05054767 0.04361075 0.44491672 0.2976096  0.53099554]]


In [65]:
#resultado
resultado = dot(MP1, SCM1)
resultado*100

array([44.40473365, 17.27765526, 14.30308187,  9.14928511, 14.86524412])

## julio



In [17]:

k = ([1,2,7],
     [1/2,1,5],
     [1/7,1/5,1])

k = array(k)
Nk=NC(k)
kM=somaL(Nk)/3
kM

array([0.59071906, 0.33382107, 0.07545987])

In [19]:
#consistencia
lmax = sum(dot(k,kM)/kM)/3
CI = (lmax-3)/(3-1)
IA = .58
RC = CI/IA
RC


np.float64(0.012221545328458252)

In [20]:
lmax

np.float64(3.0141769925810116)